### ISSUE TITLE
zkSNARK Circuit Design

### ISSUE THREAD

**Issue by SRCoughlin** [GunClear/Gunero#2]
Identify and design libsnark circuits:

- [x] Whitelist inclusion proof
- [ ] Gunkey spendability proof (nullifier, etc.)
- [ ] Full transaction spend proof

Validate it working

**Comment by fubuloubu** [comment]
Moved to Silencer repo

Authlist membership proof: https://github.com/GunClear/Silencer/issues/1
Gunkey spendability proof: https://github.com/GunClear/Silencer/issues/2
Full transaction spend proof: https://github.com/GunClear/Silencer/issues/3
