### ISSUE TITLE
Transaction Design

### ISSUE THREAD

**Issue by SRCoughlin** [GunClear/Gunero#3]
Implement a transaction that works using the snark circuit

Uses Plasma Cash design:
Requires: Simple MT of Gunkey: spending proofs
1. Verify spendability (whitelist inclusion of Tx and Rx, whitelist of Gunkey)
2. Replace old UTXO with new one
3. Update Simple MT

Depends on #2

**Comment by fubuloubu** [comment]
Defined in update in https://github.com/GunClear/Yellowpaper/issues/2
